# docker-compose for development of ubersystem

web:
  image: magfest/uberdev
  links:
    - db
  ports:
    - "8282:8282"
  volumes:
    - app:/mnt/app
db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=m13
    - POSTGRES_USER=m13
    - POSTGRES_DB=m13