# docker-compose for development of ubersystem

web:
  build: .
  links:
    - db
    - redis
  ports:
    - "8282:8282"
  volumes:
    - ./src:/app/plugins
  restart: always
  environment:
    - DB_CONNECTION_STRING=postgresql://uber_db:uber_db@rams_db:5432/uber_db
db:
  image: postgres
  name: rams_db
  environment:
    - POSTGRES_PASSWORD=uber_db
    - POSTGRES_USER=uber_db
    - POSTGRES_DB=uber_db
redis:
  image: redis
