# docker-compose for production of ubersystem
version: "3"
services: 
  lb:
    build: lb
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    env_file: $SECRETS_DIR/lb-env
  web:
    build: .
    restart: always
    links:
      - db
    env_file: $SECRETS_DIR/web-env
  db:
    build: postgres
    container_name: rams_db
    volume_driver: local
    volumes:
      - rams_db_data:/var/lib/postgresql/data
    env_file: $SECRETS_DIR/db-env
  redis:
    image: redis
    container_name: rams_redis
  rabbitmq:
    container_name: rams_rabbit
    image: rabbitmq:alpine
    env_file: $SECRETS_DIR/rabbit-env
  celery-beat:
    build: .
    links:
      - db
      - rabbitmq
    command: ['celery-beat']
  celery-worker:
    build: .
    links:
      - db
      - rabbitmq
    command: ['celery-worker']
